### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by xlijk** [goodrain/rainbond-ui#1]
node: v10.11.0
npm: 6.4.1

I get this error on build: 

`TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:258:10)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
    at nodeDeprecate (/src/github.com/goodrain/rainbond-ui/node_modules/deprecate/index.js:22:22)
    at deprecate (/src/github.com/goodrain/rainbond-ui/node_modules/deprecate/index.js:11:3)
    at Object.<anonymous> (/src/github.com/goodrain/rainbond-ui/node_modules/af-webpack/lib/getConfig.js:81:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/src/github.com/goodrain/rainbond-ui/node_modules/af-webpack/getConfig.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)`

Any idea ?

**Comment by barnettZQG** [comment]
@xlijk try to reinstall dependences. change all dependences version to min value.

**Comment by xlijk** [comment]
thanks for your reply, but no success yet. 

anybody has working package.json ?

**Comment by barnettZQG** [comment]
@Gumplefik 
This suggestion is useful.
